name: Push to main
on:
  push:
    branches:
      - main
    paths:
      - 'profiles/**'
      - 'catalogs/**'
      - 'component-definitions/**'
      - 'md_comp/**'
      - 'rules/**'

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  transform-and-regenerate:
    name: Rules Transform and Content Syncing
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Clone
        uses: actions/checkout@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Transform rules
        uses: ./.github/actions/transform-rules
    
  autosync:
    name: Automatically Sync Content
    needs: transform-and-regenerate
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Clone
        uses: actions/checkout@v4
        with:
          ref: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: AutoSync
        id: autosync
        uses: RedHatProductSecurity/trestle-bot/actions/autosync@main
        with:
          markdown_path: "md_comp"
          oscal_model: "compdef"
          commit_message: "Autosync component definition content [skip ci]"
      
      
