name: Push to main
on:
  push:
    branches:
      - main
    paths:
      - 'profiles/**'
      - 'catalogs/**'
      - 'component-definitions/**'
      - 'md_comp/**'
      - 'rules/**'

jobs:

  rules-transform:
    name: Rules Transform
    runs-on: ubuntu-latest
    steps:
      - name: Generate app token
        uses: tibdex/github-app-token@v2.1.0
        id: get_installation_token
        with: 
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
          permissions: >-
            {"contents": "write"}
      - name: Clone
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}
          token: ${{ steps.get_installation_token.outputs.token }}
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            rules:
              - 'rules/**'
      - name: Transform
        if: steps.changes.outputs.rules == 'true'
        id: transform
        uses: RedHatProductSecurity/trestle-bot/actions/rules-transform@v0.7.1
        with:
          commit_message: "Auto-transform rules content [skip ci]"
  
  autosync:
    name: Auto-update content
    runs-on: ubuntu-latest
    needs: rules-transform
    steps:
      - name: Generate app token
        uses: tibdex/github-app-token@v2.1.0
        id: get_installation_token
        with: 
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
          permissions: >-
            {"contents": "write"}
      - name: Clone
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}
          token: ${{ steps.get_installation_token.outputs.token }}
      - name: Sync
        id: autosync
        uses: RedHatProductSecurity/trestle-bot/actions/autosync@v0.7.1
        with:
          markdown_path: "md_comp"
          oscal_model: "compdef"
          commit_message: "Auto-sync component definition content [skip ci]"